ALTER TABLE knowledge_articles
  ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS images TEXT NOT NULL DEFAULT '[]';

ALTER TABLE glossary_terms
  ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS images TEXT NOT NULL DEFAULT '[]';

